"use client";

import Header from "@/components/Header";
import { Inter } from "next/font/google";
import { useEffect, useState } from "react";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Music App",
//   description: "Generated by Emran Ibn Shayed",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    setTimeout(() => {
      setLoading(false);
    }, 500);
  }, []);

  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
          {/* {loading ? (
            <FullPageLoader />
          ) : ( */}
          <div>
            <Header />
            <main>{children}</main>
          </div>
          {/* )} */}
        </div>
      </body>
    </html>
  );
}
